name: surya testing 31Aug25

on:
  push:
    branches:
    - main
    - surya1
    - feature/*
jobs:
  production-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    #OIDC token lene ke liye zaruri hai
      contents: read
    steps:  
        - name: Azure Login
          uses: Azure/login@v2.3.0
          with:            
              client-id: c578a89c-8feb-4f2f-88cb-8c48581bd989
              tenant-id: defb5fbe-74e0-453c-9d33-594936bf34c5
              subscription-id: 81cc1915-8d88-419e-8fa3-0178811761bd
              environment: azurecloud
              auth-type: SERVICE_PRINCIPAL
              
        - name: Install Terraform
          uses: little-core-labs/install-terraform@v2.0.0
          with:
            version: latest

        - name: Terraform init
          uses: robburger/terraform-pr-commenter@v1.5.0
          with:
            commenter_type: init

        - name: Terraform plan
          uses: robburger/terraform-pr-commenter@v1.5.0
          with:
            commenter_type: plan
    
            
            
            
                                    
              
                





