name: surya testing 31Aug25

on:
  push:
    branches:
    - main
    - surya1
    - feature/*
jobs:
  production-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    #OIDC token lene ke liye zaruri hai
      contents: read
    steps:  
        - name: Azure Login
          uses: Azure/login@v2.3.0
          with:
              # ClientId of the Azure Service principal created.
              client-id: c578a89c-8feb-4f2f-88cb-8c48581bd989
              # TenantId of the Azure Service principal created.
              tenant-id: defb5fbe-74e0-453c-9d33-594936bf34c5
              # Azure subscriptionId
              subscription-id: 81cc1915-8d88-419e-8fa3-0178811761bd
              # Name of the environment. Supported values are azurecloud, azurestack, azureusgovernment, azurechinacloud, azuregermancloud. Default being azurecloud
              environment: azurecloud
              # The type of authentication. Supported values are SERVICE_PRINCIPAL, IDENTITY. Default value is SERVICE_PRINCIPAL
              auth-type: SERVICE_PRINCIPAL
              
        - name: Install Terraform
              # You may pin to the exact commit or the version.
              # uses: little-core-labs/install-terraform@1e577535d279f1999a5abf60337ddc3ff225e79d
          uses: little-core-labs/install-terraform@v2.0.0
          with:
            # Version of terraform to download
            version: latest

        - name: Terraform PR Commenter
          uses: robburger/terraform-pr-commenter@v1.5.0
          with:
            # The type of comment. Options: [fmt, init, plan]
            commenter_type: init

        - name: Terraform PR Commenter
          uses: robburger/terraform-pr-commenter@v1.5.0
          with:
            # The type of comment. Options: [fmt, init, plan]
            commenter_type: plan
    
            
            
            
                                    
              
                





